/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MossingerApp;

import Beans.Pedidos.Orcamentos;
import Beans.Produtos.Produtos;
import DAO.ListarProdutosDAO;
import DAO.ReadOrcDAO;
import DAO.UpdateOrcDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddProduto extends javax.swing.JFrame {

    /**
     * Creates new form AddProduto
     */
    public AddProduto() {
        initComponents();
    }
    
    String protocolo = null;
    Principal principal = null;
    
    public void dados(String protocolo,Principal principal){
        
        this.protocolo = protocolo;
        this.principal = principal;
        
        
    }

    
    
    
 
    public void verificarequipamento(){
        
        ListarProdutosDAO listarprodutos = new ListarProdutosDAO();
        ArrayList<Produtos> pLista = listarprodutos.listarProdutos(comboEquip.getItemAt(comboEquip.getSelectedIndex()));
        comboModelo.removeAllItems();
       
        
        
        for(int i = 0; i < pLista.size(); i++){
            
            comboModelo.addItem(pLista.get(i).getpmodelo());
         
            
            
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lSelectEQ = new javax.swing.JLabel();
        comboEquip = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        comboModelo = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionar Equipamento", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        lSelectEQ.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lSelectEQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lSelectEQ.setText("Selecionar Equipamento");

        comboEquip.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        comboEquip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secador", "Fornalha", "Elevador", "Transportador Helicoidal", "Transportador Redler", "Pré-Limpeza" }));
        comboEquip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEquipItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Modelo");

        comboModelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnOK.setText("Ok");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboEquip, 0, 372, Short.MAX_VALUE)
            .addComponent(comboModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lSelectEQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lSelectEQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboEquipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEquipItemStateChanged
     
        verificarequipamento();
        
    }//GEN-LAST:event_comboEquipItemStateChanged

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
     

        String produto = comboEquip.getItemAt(comboEquip.getSelectedIndex());
        ListarProdutosDAO listarprodutos = new ListarProdutosDAO();
        ArrayList<Produtos> pLista = listarprodutos.listarProdutos(produto);
        
        if(produto.equals("Fornalha")){
            
        String modelo = comboModelo.getItemAt(comboModelo.getSelectedIndex());
        
        for(int i = 0; i < pLista.size(); i++){
            
        if(pLista.get(i).getpmodelo().equals(modelo)){
            
        Long fornalhaID = pLista.get(i).getId();
              
               Orcamentos orcamento = new Orcamentos();
               UpdateOrcDAO dao = new UpdateOrcDAO();
               ReadOrcDAO readorc = new ReadOrcDAO();
               ArrayList<Orcamentos> oLista = readorc.lerOrcamentos();
               
               for(int o = 0; o < oLista.size(); o++){

                   if(Long.toString(oLista.get(o).getProtocolo()).equals(protocolo)){
                       
                         orcamento.setListaprodutos(oLista.get(o).getListaprodutos() + fornalhaID + ";");
                         orcamento.setProtocolo(Long.parseLong(protocolo));
                         dao.update(orcamento);
               
                   }
               }
           }
        }
        }
        
        
        principal.atualizarTabelaProdutos();
        
        this.dispose();
        
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> comboEquip;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lSelectEQ;
    // End of variables declaration//GEN-END:variables
}
