/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MossingerApp;

import Beans.Pedidos.Orcamentos;
import DAO.ReadOrcDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class OrcamentosForm extends javax.swing.JFrame {

    /**
     * Creates new form OrcamentosForm
     */
    public OrcamentosForm() {
        initComponents();
    }
    
    
    
    String idcliente = "0000000000";
    String nomecliente = "";
    String rzs = "";
    String endereco = "";
    String cidade = "";
    String cnpj = "";
    String cpf = "";
    String email = "";
    String celular = "";
    String telefone = "";
    String cep = "";
    String datanasci = "";
    String uf = "";
    String banco = "";
    String agencia = "";
    String contatobanco = "";
    Principal principal;
    MClientes mcliente;
    Boolean editar = false;
    
    
    
    
    
    
    
    
    
    public void getcontext(MClientes mcliente,String nome, String id,String rzs,
            String endereco,String cidade,String cnpj,String cpf,String email,String celular,
            String telefone,String cep,String datanasci,String uf,String banco,
            String agencia,String contatobanco,Principal principal){
        
        txtNomeCliente.setText(nome);
        
        this.idcliente = id;
        this.nomecliente = nome;
        this.rzs = rzs;
        this.endereco = endereco;
        this.cidade = cidade;
        this.cnpj = cnpj;
        this.cpf = cpf;
        this.email = email;
        this.celular = celular;
        this.telefone = telefone;
        this.cep = cep;
        this.datanasci = datanasci;
        this.uf = uf;
        this.banco = banco;
        this.agencia = agencia;
        this.contatobanco = contatobanco;
        this.principal = principal;
        this.mcliente = mcliente;
        
        
        principal.setEnabled(false);
        mcliente.setEnabled(false);
        
        
        Orcamentos orcamento = new Orcamentos();
        ReadOrcDAO readorc = new ReadOrcDAO();
         ArrayList<Orcamentos> oLista = readorc.lerOrcamentos();
         DefaultTableModel model = (DefaultTableModel) tabOrcamentos.getModel();
         model.setNumRows(0);
        
         
           for(int i = 0; i < oLista.size(); i++){
               
               
               if(Long.toString(oLista.get(i).getIdcliente()).equals(id)){
                   
                    model.addRow(new Object[]{
                                            
                                          oLista.get(i).getProtocolo(),
                                          oLista.get(i).getDatapedido(),
                                                   
                                  
                                       });  
                   
               }
               
               
           }
           
           
           
           
           
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabOrcamentos = new javax.swing.JTable();
        editarOrcamento = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Orçamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabOrcamentos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabOrcamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Protocolo", "DATA", "Valor Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabOrcamentos);

        editarOrcamento.setText("Editar");
        editarOrcamento.setToolTipText("");
        editarOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarOrcamentoActionPerformed(evt);
            }
        });

        jButton3.setText("Deletar");

        txtNomeCliente.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNomeCliente.setText("Matheus Henrique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(editarOrcamento)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarOrcamento)
                    .addComponent(jButton3)
                    .addComponent(txtNomeCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
  
        // Voltar Ao normal
        
        if(!editar){
        mcliente.setEnabled(true);
        principal.setVisible(true);
        mcliente.setVisible(true);
        }
        
        
    }//GEN-LAST:event_formWindowClosed

    private void editarOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarOrcamentoActionPerformed

        editar= true;
        
        String protocolo = tabOrcamentos.getValueAt(tabOrcamentos.getSelectedRow(), 0).toString();
        
        principal.preencher(protocolo, idcliente,nomecliente,rzs, endereco, cidade, cnpj, cpf, email, Long.parseLong(celular),Long.parseLong(telefone), Integer.parseInt(cep), datanasci, uf, banco, agencia, contatobanco);
        
        mcliente.dispose();
  
        this.dispose();
        
        
    }//GEN-LAST:event_editarOrcamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrcamentosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrcamentosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrcamentosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrcamentosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrcamentosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarOrcamento;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabOrcamentos;
    private javax.swing.JLabel txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
