/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MossingerApp;

import Beans.Clientes.Cliente;
import Beans.Pedidos.Orcamentos;
import Beans.Produtos.Produtos;
import DAO.ClienteDAO;
import DAO.ListarClientesDAO;
import DAO.ListarProdutosDAO;
import DAO.ReadOrcDAO;
import DAO.UpdateOrcDAO;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.PDPageContentStream.AppendMode;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType0Font;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        initComponents();

       
    }
    
    public void carregarorcamento(){
        
        
        
    }
    
    public void atualizarTabelaProdutos(){
        
       // Orcamentos orcamento = new Orcamentos();
        ReadOrcDAO readorc = new ReadOrcDAO();
         ArrayList<Orcamentos> oLista = readorc.lerOrcamentos();
         DefaultTableModel model = (DefaultTableModel) tabProdutos.getModel();
         model.setNumRows(0);
        
         
           for(int i = 0; i < oLista.size(); i++){
                
            
                  
                    if(Long.toString(oLista.get(i).getProtocolo()).equals(txtProtocolo.getText().toString())){
                
                     String[] split = oLista.get(i).getListaprodutos().split(";");
                 // 
                 
          
                     for(int k = 0; k < split.length ; k++){
                
                         if(!split[k].toString().equals("")){ // FORNALHA
                             
        ListarProdutosDAO listarprodutos = new ListarProdutosDAO();
        ArrayList<Produtos> pLista = listarprodutos.listarProdutos("fornalha");
                             
                          for(int y = 0; y < pLista.size(); y++){
                              
                              if(Long.toString(pLista.get(y).getId()).equals(split[k].toString())){
                                  
                                      model.addRow(new Object[]{
                                            
                                          pLista.get(y).getId(),
                                          "Fornalha",
                                          pLista.get(y).getpmodelo(),
                                          pLista.get(y).getCusto(),
                                                   
                                  
                                       });  
                              }
   
                          }    

                     }
 
                 }

                    }
  
            }
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo01 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        edtNome = new javax.swing.JTextField();
        edtRazaoSocial = new javax.swing.JTextField();
        edtEndereco = new javax.swing.JTextField();
        edtCidade = new javax.swing.JTextField();
        edtCNPJ = new javax.swing.JTextField();
        edtCPF = new javax.swing.JTextField();
        edtEmail = new javax.swing.JTextField();
        edtCelular = new javax.swing.JTextField();
        edtTelefone = new javax.swing.JTextField();
        edtCep = new javax.swing.JTextField();
        edtNasci = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtProtocolo = new javax.swing.JLabel();
        nrCliente = new javax.swing.JLabel();
        txtIDCliente = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDATA = new javax.swing.JLabel();
        coUF = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabProdutos = new javax.swing.JTable();
        btnRemoverProd = new javax.swing.JButton();
        Detalhes = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        edtBanco = new javax.swing.JTextField();
        edtAgencia = new javax.swing.JTextField();
        edtBContato = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnClientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnGerarPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mossinger Máquinas - Gerador de Contratos");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(254, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        logo01.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logonovo.png"))); // NOI18N
        logo01.setMaximumSize(new java.awt.Dimension(300, 300));
        logo01.setMinimumSize(new java.awt.Dimension(300, 300));
        logo01.setPreferredSize(new java.awt.Dimension(200, 200));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Pedido de Equipamentos Mossinger");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cliente", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        edtNome.setText("Nome");

        edtRazaoSocial.setText("Razão Social");

        edtEndereco.setText("Endereço");

        edtCidade.setText("Cidade");

        edtCNPJ.setText("CNPJ");

        edtCPF.setText("CPF");

        edtEmail.setText("E-Mail");

        edtCelular.setText("Celular");

        edtTelefone.setText("Telefone");

        edtCep.setText("CEP");

        edtNasci.setText("Data de Nascimento");
        edtNasci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNasciActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Controle", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Protocolo");

        txtProtocolo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtProtocolo.setForeground(new java.awt.Color(0, 0, 0));
        txtProtocolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtProtocolo.setText("0000000000");

        nrCliente.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nrCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nrCliente.setText("Cliente Nº:");

        txtIDCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIDCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIDCliente.setText("0000000000");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA");

        txtDATA.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDATA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDATA.setText("10/10/2022");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIDCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtProtocolo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nrCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDATA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nrCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDATA, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        coUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "São Paulo", "Rio De Janeiro", "Mato Grosso" }));

        jLabel2.setText("UF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(edtCidade, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtRazaoSocial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(edtNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtCNPJ)
                    .addComponent(edtCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtEmail)
                    .addComponent(edtCelular)
                    .addComponent(edtTelefone)
                    .addComponent(edtCep)
                    .addComponent(edtNasci, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(coUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(coUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(edtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtNasci, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Lista de Equipamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12)), "", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tabProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Modelo", "Custo Fabricação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabProdutos);

        btnRemoverProd.setText("Remover");
        btnRemoverProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdActionPerformed(evt);
            }
        });

        Detalhes.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        Detalhes.setText("Detalhes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Detalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoverProd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoverProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Detalhes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Agente", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Referência Bancária", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        edtBanco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtBanco.setText("Banco");

        edtAgencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtAgencia.setText("Agência");

        edtBContato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        edtBContato.setText("Contato");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(edtBanco, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(edtAgencia, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(edtBContato)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(edtBanco, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtBContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setText("Adicionar Produtos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Dados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        btnClientes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProdutos.setText("Produtos");

        btnPedidos.setText("Pedidos");
        btnPedidos.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProdutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel11.setToolTipText("");

        jButton3.setText("Limpar");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnGerarPDF.setText("Gerar Proposta");
        btnGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGerarPDF, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarPDF)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo01, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtNasciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNasciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNasciActionPerformed

    
 
    
    
    private void btnGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPDFActionPerformed
       
      
try {
    
    
    PDDocument document = PDDocument.load(new File("C:/Users/User/Desktop/modelo de proposta mossinger/pdf/Proposta_Mossinger01.pdf"));
    PDPage page = document.getPage(0);
    PDFont font = PDType0Font.load(document, new File("c:/windows/fonts/arial.ttf"));
    PDPageContentStream contentStream = new PDPageContentStream(document, page,AppendMode.APPEND, true, true);

    contentStream.beginText();
    contentStream.setFont(font, 12);
    contentStream.newLineAtOffset(100, 700);
    contentStream.showText(edtNome.getText().toString());
    contentStream.endText();
    
    contentStream.beginText();
    contentStream.newLineAtOffset(100, 685);
    contentStream.showText(edtEndereco.getText().toString());
    contentStream.endText();
    
    contentStream.beginText();
    contentStream.newLineAtOffset(100, 670);
    contentStream.showText(edtCidade.getText().toString());
    contentStream.endText();
    
    contentStream.beginText();
    contentStream.newLineAtOffset(100, 655);
    contentStream.showText(edtTelefone.getText().toString());
    contentStream.endText();
    
    contentStream.beginText();
    contentStream.newLineAtOffset(450, 745);
    contentStream.showText(txtDATA.getText().toString());
    contentStream.endText();
    
    
    contentStream.close();
    
    document.save("C:/Users/User/Desktop/modelo de proposta mossinger/pdf/gerado/PaginaPrincipal.pdf");

    document.close();
    
   
    
    
} catch (IOException e) {
    e.printStackTrace();
} 


    
   for(int i = 0; i < tabProdutos.getRowCount(); i++){
        
     if(tabProdutos.getValueAt(i, 1).toString().equals("Fornalha")){
           
           try {
               
    
    PDDocument document = PDDocument.load(new File("C:/Users/User/Desktop/modelo de proposta mossinger/pdf/Fornalha_10-20cav.pdf"));
    
    
    PDPage page = document.getPage(0);
    PDFont font = PDType0Font.load(document, new File("c:/windows/fonts/arial.ttf"));
    PDPageContentStream contentStream = new PDPageContentStream(document, page,AppendMode.APPEND, true, true);

    
    //escreve modeloEquip
    contentStream.beginText();
    contentStream.setFont(font, 12);
    contentStream.newLineAtOffset(95,738);
    contentStream.showText("FM " + tabProdutos.getValueAt(i, 2).toString());
    contentStream.endText();
    
        
        //escreve nomecliente
     contentStream.beginText();
    contentStream.setFont(font, 12);
    contentStream.newLineAtOffset(95, 722);
    contentStream.showText(edtNome.getText().toString());
    contentStream.endText();
    
            //escreve cidade
     contentStream.beginText();
    contentStream.setFont(font, 12);
    contentStream.newLineAtOffset(100, 706);
    contentStream.showText(edtCidade.getText().toString());
    contentStream.endText();
    
            //escreve nomedovendedor
     contentStream.beginText();
    contentStream.setFont(font, 12);
    contentStream.newLineAtOffset(115, 680);
    contentStream.showText("Sebastião");
    contentStream.endText();
    
    
    
    
    contentStream.close();
    String doccound = "0" + Integer.toString(i);
    
    document.save("C:/Users/User/Desktop/modelo de proposta mossinger/pdf/gerado/Fornalha" + doccound + ".pdf");

    document.close();
    
    
          } catch (IOException e) {
    e.printStackTrace();
} 
           
           
           
           
           
          
     }

        
     
     
     
   }
    
           
    



        
        
    }//GEN-LAST:event_btnGerarPDFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        boolean abrir = true;
        
        if(!edtNome.isEditable()){
            
            abrir = true;
            
        } else if(!txtProtocolo.getText().toString().equals("0000000000")){
            
            abrir = true;
            
        } else if(!txtIDCliente.getText().toString().equals("0000000000")){
            
             abrir = true;
        } else {
            
             abrir = false;
            
        }
        
        
        if(abrir){
        AddProduto add= new AddProduto();// obj created for class Second()
	add.dados(txtProtocolo.getText().toString(),this);//Execute the method my_update to pass str
        add.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	add.setVisible(true); // Open the Second.java window
        } else {
            
            JOptionPane.showMessageDialog(null, "É necessário criar ou carregar um orçamento antes de adicionar produtos.");
            
        }
   
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    private boolean verificarCamposCliente(){
        
        if(edtNome.getText().contains("Nome")){
            return true;
        } else if(edtRazaoSocial.getText().contains("Razão Social")){
                
            return true;
            } else if(edtEndereco.getText().contains("Endereço")){
                
            return true;
            } else if(edtCidade.getText().contains("Cidade")){
                
            return true;
            } else if(edtCNPJ.getText().contains("CNPJ")){
                
            return true;
            } else if(edtCPF.getText().contains("CPF")){
                
            return true;
            } else if(edtEmail.getText().contains("E-Mail")){
                
            return true;
            } else if(edtCelular.getText().contains("Celular")){
                
            return true;
            } else if(edtTelefone.getText().contains("Telefone")){
                
            return true;
            } else if(edtCep.getText().contains("CEP")){
                
            return true;
            } else if(edtNasci.getText().contains("Nascimento")){
                
            return true;
            } else if(edtBanco.getText().equals("Banco")){
                
            return true;
            } else if(edtAgencia.getText().contains("Agência")){
                
            return true;
            } else if(edtBContato.getText().contains("Contato")){
                
            return true;
            } else  {
                
                return false;
            }
     
     
        
    }
    
    private boolean verificarClienteExistente(){
        
        try {
            
            ListarClientesDAO  listarclientesdao = new ListarClientesDAO();
             ArrayList<Cliente> cLista = listarclientesdao.listarClientes();
             
             for(int i = 0; i < cLista.size(); i++){
                
               
                 if(cLista.get(i).getCpf().toString().equals(edtCPF.getText().toString())){
                     
                     return true;
                 } else  if(cLista.get(i).getCnpj().toString().equals(edtCNPJ.getText().toString())){
                     
                     return true;
                 } else  if(cLista.get(i).getEmail().toString().equals(edtEmail.getText().toString())){
                     
                     return true;
                 } 
                    
      
             }
             
        
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Ixi Deu erro :" + e);
        }
        
          return false;
    }
    
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        
        if(!verificarCamposCliente()){
       
            
            if(!verificarClienteExistente()){
            
        Cliente cliente = new Cliente(edtNome.getText().toString(),edtRazaoSocial.getText().toString(),edtEndereco.getText().toString(),edtCidade.getText().toString(),edtCNPJ.getText().toString(),edtCPF.getText().toString(),edtEmail.getText().toString(),Long.parseLong(edtCelular.getText().toString()),Long.parseLong(edtTelefone.getText().toString()),0,Integer.parseInt(edtCep.getText().toString()),edtNasci.getText().toString(),coUF.getSelectedItem().toString(),edtBanco.getText().toString(),edtAgencia.getText().toString(),edtBContato.getText().toString());
        ClienteDAO clientedao = new ClienteDAO();   
         if ((clientedao.save(cliente))){
            System.out.println("Salvo com Sucesso");
        } else {
          System.err.println("Deu merda");
        }
         
            } else {
                
                 JOptionPane.showMessageDialog(null, "O cliente já está cadastrado, favor procurar na lista de clientes.");
                
            }
         
         
        } else {
            
            JOptionPane.showMessageDialog(null, "Por favor, preencha os campos referentes aos dados do Cliente.");
            
        }
         
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    public void preencher(String protocolo, String idCliente,String nome, String razaosocial, String endereco, String cidade,
            String cnpj, String cpf, String email,Long celular, Long telefone,int cep, String datanascimento,String uf,String banco,
            String agencia, String contato){
        
        
        
       txtIDCliente.setText(idCliente);
       txtProtocolo.setText(protocolo);
       edtNome.setText(nome);
       edtRazaoSocial.setText(razaosocial);
       edtEndereco.setText(endereco);
       edtCidade.setText(cidade);
       edtCNPJ.setText(cnpj);
       edtCPF.setText(cpf);
       edtEmail.setText(email);
       edtCelular.setText(celular.toString());
       edtTelefone.setText(telefone.toString());
       edtCep.setText(Integer.toString(cep));
       edtNasci.setText(datanascimento);
       edtBanco.setText(banco);
       coUF.getModel().setSelectedItem(uf);
       edtAgencia.setText(agencia);
       edtBContato.setText(contato);
       
     
       
       
       
       
       
       edtNome.setEnabled(false);
       edtRazaoSocial.setEnabled(false);
       edtEndereco.setEnabled(false);
       edtCidade.setEnabled(false);
       edtCNPJ.setEnabled(false);
       edtCPF.setEnabled(false);
       edtEmail.setEnabled(false);
       edtCelular.setEnabled(false);
       edtTelefone.setEnabled(false);
       edtCep.setEnabled(false);
       edtNasci.setEnabled(false);
       edtBanco.setEnabled(false);
       edtAgencia.setEnabled(false);
       edtBContato.setEnabled(false);
       
       
       
         atualizarTabelaProdutos();
         
         this.setEnabled(true);
        
    }
    
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
    
        MClientes mclientes = new MClientes();// obj created for class Second()
	mclientes.getcontext(this);//Execute the method my_update to pass str
        mclientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setEnabled(false);
	mclientes.setVisible(true); // Open the Second.java window
   
        
        
        
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnRemoverProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdActionPerformed
       
        //Remove Produto Selecionado
        
        if(!txtProtocolo.getText().toString().equals("0000000000") && !edtNome.isEnabled()){
            
        
            String removerid =  tabProdutos.getValueAt(tabProdutos.getSelectedRow(), 0).toString() + ";";
            
            
            
            
        ReadOrcDAO readorc = new ReadOrcDAO();
        ArrayList<Orcamentos> oLista = readorc.lerOrcamentos();
        Orcamentos orcamento = new Orcamentos();
        UpdateOrcDAO dao = new UpdateOrcDAO();

 
        
        for(int i = 0; i < oLista.size(); i++){

            
           
if(Long.toString(oLista.get(i).getProtocolo()).equals(txtProtocolo.getText().toString())){
    
    String listaprodutos = oLista.get(i).getListaprodutos();

    
    
    if(listaprodutos.contains(removerid)){
    // JOptionPane.showMessageDialog(null, listaprodutos.replaceFirst(removerid,""));

    }
    
  
     if(!removerid.isEmpty()){
 
  orcamento.setProtocolo(oLista.get(i).getProtocolo());    
  orcamento.setListaprodutos(listaprodutos.replaceFirst(removerid,""));
  dao.update(orcamento);
      }
    
}
     


}
            
            
            
        }
        


        atualizarTabelaProdutos();
    
    }//GEN-LAST:event_btnRemoverProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Detalhes;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnGerarPDF;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnRemoverProd;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> coUF;
    private javax.swing.JTextField edtAgencia;
    private javax.swing.JTextField edtBContato;
    private javax.swing.JTextField edtBanco;
    private javax.swing.JTextField edtCNPJ;
    private javax.swing.JTextField edtCPF;
    private javax.swing.JTextField edtCelular;
    private javax.swing.JTextField edtCep;
    private javax.swing.JTextField edtCidade;
    private javax.swing.JTextField edtEmail;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNasci;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtRazaoSocial;
    private javax.swing.JTextField edtTelefone;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo01;
    private javax.swing.JLabel nrCliente;
    private javax.swing.JTable tabProdutos;
    private javax.swing.JLabel txtDATA;
    private javax.swing.JLabel txtIDCliente;
    private javax.swing.JLabel txtProtocolo;
    // End of variables declaration//GEN-END:variables
}
